# Generated by Django 3.2.7 on 2021-10-03 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikedisplay',
            name='bikeImage',
            field=models.ImageField(upload_to='static/dbImages/'),
        ),
    ]
