# Generated by Django 3.2.7 on 2021-10-03 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApp', '0002_alter_bikedisplay_bikeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikedisplay',
            name='bikeImage',
            field=models.ImageField(upload_to=''),
        ),
    ]
