# Generated by Django 3.2.7 on 2021-10-04 09:12

import dashboardApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApp', '0004_alter_bikedisplay_bikeimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='bikeServiceRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceUser', models.CharField(max_length=50)),
                ('serviceCompany', models.CharField(max_length=50)),
                ('serviceModel', models.CharField(max_length=50)),
                ('serviceNumber', models.CharField(max_length=50)),
                ('serviceColor', models.CharField(max_length=50)),
                ('pickup', models.CharField(max_length=50)),
                ('delivery', models.CharField(max_length=50)),
                ('kmcovered', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('problem', models.TextField()),
                ('completed', models.CharField(default='Not Completed', max_length=100)),
                ('serviceDate', models.DateField(validators=[dashboardApp.models.bikeServiceRequestModel.validate_date])),
                ('serviceTime', models.TimeField()),
                ('deliveryTime', models.TimeField()),
            ],
        ),
    ]
