# Generated by Django 3.2.7 on 2021-10-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApp', '0006_alter_bikeservicerequestmodel_serviceuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikeservicerequestmodel',
            name='serviceUser',
            field=models.CharField(max_length=50),
        ),
    ]
