# Generated by Django 3.2.7 on 2021-10-06 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboardApp', '0007_alter_bikeservicerequestmodel_serviceuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikeservicerequestmodel',
            name='serviceUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
