# Generated by Django 3.2.7 on 2021-10-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApp', '0008_alter_bikeservicerequestmodel_serviceuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='bikeCompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bikeCompanyNames', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='userBikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bikeModel', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='bikeservicerequestmodel',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
