# Generated by Django 3.2.7 on 2021-10-06 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApp', '0009_auto_20211006_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikeservicerequestmodel',
            name='serviceCompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardApp.bikecompanymodel'),
        ),
        migrations.AlterField(
            model_name='bikeservicerequestmodel',
            name='serviceModel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboardApp.userbikemodel'),
        ),
    ]
