# Generated by Django 3.2.7 on 2021-10-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApp', '0010_auto_20211006_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikeservicerequestmodel',
            name='serviceNumber',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
