# Generated by Django 3.2.7 on 2021-10-07 07:30

import dashboardApp.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApp', '0011_alter_bikeservicerequestmodel_servicenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikeservicerequestmodel',
            name='serviceDate',
            field=models.DateField(default=django.utils.timezone.now, validators=[dashboardApp.models.bikeServiceRequestModel.validate_date]),
        ),
        migrations.AlterField(
            model_name='bikeservicerequestmodel',
            name='serviceTime',
            field=models.TimeField(auto_now=True),
        ),
    ]
