# Generated by Django 3.2.7 on 2021-10-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApp', '0012_auto_20211007_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikedisplay',
            name='bikeNumber',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
