# Generated by Django 3.2.7 on 2021-10-24 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardApp', '0014_auto_20211010_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedBackFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('userFeedBack', models.TextField()),
                ('feedBackTime', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
