# Generated by Django 3.2.7 on 2021-10-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='blogImage',
            field=models.ImageField(default=' ', upload_to='blogImages'),
            preserve_default=False,
        ),
    ]
