# Generated by Django 3.2.7 on 2021-10-03 16:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_blogmodel_blogimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='blogContent',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
